package audio

import (
	"encoding/binary"
	"fmt"
	"math"
	"os"
	"runtime"
	"sync"
	"sync/atomic"
	"time"

	"github.com/ebitengine/oto/v3"
)

// AYSource is the minimal interface that the audio system needs from an AY
// sound chip implementation. It is satisfied by *ay.AY but kept as an
// interface here so the audio package does not need to import the ay package
// (which would create a dependency cycle through the ULA).
type AYSource interface {
	MixInto(buf []int16)
}

// DACSource is the minimal interface for the Spectrum Next's four
// 8-bit DACs. Satisfied by *next/dac.Bank. Mixes at frame-snapshot
// granularity: the current level is applied uniformly across the
// whole buffer rather than integrating individual writes within
// the frame (contrast pkg/audiodac's event-based reconstruction).
type DACSource interface {
	MixInto(buf []int16)
}

const (
	// Audio parameters
	SampleRate   = 44100
	ChannelCount = 2    // Stereo
	BitDepth     = 16   // 16-bit
	BufferSize   = 1024 // oto buffer size in samples — small enough that Read() runs ~43 times/sec, keeping playback latency low

	// SamplesPerFrame is the number of mono beeper samples one
	// emulator frame produces at SampleRate / 50Hz. The ULA pushes
	// exactly this many samples to the audio system per frame.
	SamplesPerFrame = SampleRate / 50

	// queueCapacity is the ring buffer size in mono samples — about
	// 12 frames at 50Hz (~240 ms). Wide enough to absorb scheduler
	// jitter, GC pauses, and the natural push/pull oscillation
	// between the 50Hz producer and the ~43Hz consumer.
	queueCapacity = SamplesPerFrame * 12

	// underrunCushion is the watermark the ring must refill to after a
	// TRUE underrun before real samples flow again (popBeeperSamples'
	// hysteresis). Without it the ring's steady-state depth is wherever
	// the startup transient leaves it — in practice ~0, where every
	// scheduling wobble between the 20 ms producer tick and the device
	// pull dips empty and interleaves a filler sliver ~40×/s: audible
	// stutter that no downstream (device-side) buffer can fix, because
	// the gaps are already IN the stream by then. With the hysteresis
	// the steady state sits AT the cushion instead, and a genuine
	// starvation costs one ~60 ms rebuild rather than continuous
	// crackle. The cushion is also the ring's contribution to end-to-end
	// latency — three frames balances stutter immunity against lag.
	underrunCushion = SamplesPerFrame * 3
)

// The cushion must fit in the ring with room to spare; this compile-time
// check trips if either constant's multiplier is changed on its own.
var _ [queueCapacity - underrunCushion]struct{}

// AudioSystem handles audio output for the ZX Spectrum beeper and (on 128K+
// machines) the AY-3-8912 sound chip.
//
// The beeper input is event-driven: the ULA records every speaker bit
// toggle during the frame with the T-state at which it happened, and at
// end of frame generates a fresh batch of SamplesPerFrame mono samples
// that gets pushed via PushBeeperSamples. The oto playback callback
// pulls samples from the ring buffer; on underflow it holds the last
// sample (DC) instead of clicking.
//
// The AY chip is mixed in by the playback callback at audio-sample
// rate via AYSource.MixInto, since AY samples are generated by the
// chip's own internal counters and don't need event-time alignment.
type AudioSystem struct {
	context *oto.Context
	player  *oto.Player
	reader  *audioReader

	// Beeper sample ring buffer.
	queueMu    sync.Mutex
	queue      [queueCapacity]int16
	queueHead  int   // next write position
	queueTail  int   // next read position
	queueSize  int   // number of samples currently in the buffer
	lastSample int16 // value to hold during underflow (DC, no clicks)
	// cushioning is the underrun-hysteresis state (guarded by queueMu):
	// armed when the ring runs dry, released once queueSize reaches
	// underrunCushion. While armed, popBeeperSamples delivers only the
	// decaying held level. Only the oto path consults it — the browser's
	// PullMono/AudioWorklet owns its own cushion policy.
	cushioning bool
	// Diagnostic counters (guarded by queueMu): how often the hysteresis
	// re-armed (true underruns) and how many samples the overflow path
	// discarded (drop-oldest). Producer/consumer clock drift shows up as
	// one of these climbing steadily — see the drift probe test.
	statUnderruns uint64
	statDropped   uint64
	// statPushed counts every sample ever pushed (guarded by queueMu) —
	// diagnostic, see the drift probe test.
	statPushed uint64

	// prodRateBits (math.Float64bits) is the AUTHORITATIVE production
	// rate in samples/second, reported by the frontend's frame loop
	// (executed frames × SamplesPerFrame per wall second — the FPS
	// measurement). The rate servo consumes this instead of inferring a
	// rate from push timestamps: a wall-clock estimator cannot tell "the
	// emulator is overloaded" from "production intentionally stopped"
	// (pause, .nex import, screen transition), and a single stopped
	// window poisons the estimate — the ratio then pins low while
	// production resumes at full rate, the ring overflows, and
	// drop-oldest shreds the stream (heard as garbled jingles and
	// swallowed keyclicks). The frame loop KNOWS the difference and
	// simply doesn't report while paused. Zero means "not reported yet"
	// → nominal SampleRate.
	prodRateBits atomic.Uint64

	// Optional AY-3-8912 source.
	ayMu sync.RWMutex
	ay   AYSource

	// Optional Spectrum Next DAC source.
	dacMu sync.RWMutex
	dac   DACSource

	// keepAlive is the peak amplitude of the sub-audible dither mixed into the
	// output to stop the host audio amp powering down during silence (and
	// popping on the next sound). 0 disables. Read/written only on the oto
	// goroutine path + setup, so a plain field is fine.
	keepAlive int16

	// WAV recording state. When recFile is non-nil the audio reader
	// appends each generated sample to the file as 16-bit mono PCM.
	recMu      sync.Mutex
	recFile    *os.File
	recSamples uint64
	recScratch []byte
}

// audioReader implements io.Reader on the oto playback goroutine.
type audioReader struct {
	audioSys  *AudioSystem
	buffer    []byte
	mixBuffer []int16
	ditherRNG uint32 // xorshift32 state for the keep-alive dither

	// Dynamic rate control (the oto path's clock servo). The producer
	// paces by executed emulation frames, the consumer by the audio
	// device's clock; those rates NEVER match exactly (clock drift) and
	// under sustained overload the producer falls far behind. The servo
	// watches ring depth each pull and resamples the popped chunk by
	// `ratio` (source samples per output sample): depth below target →
	// ratio sinks → the ring drains slower — micro-drift becomes an
	// inaudible pitch trim, and sustained overload becomes continuously
	// slowed audio (real-hardware-style slowdown) instead of
	// machine-gun filler gaps.
	//
	// Control shape: integrating controllers on an integrating plant
	// (ring depth) double-integrate and hunt audibly, so the servo is
	// FEED-FORWARD + weak proportional instead — nothing to oscillate.
	// The feed-forward term is the frontend-reported production rate
	// (see AudioSystem.prodRateBits): ratio glides toward
	// reportedRate/SampleRate, so a machine emulating at 80% speed is
	// consumed at 80% rate by construction, and a small depth-centering
	// term nudges the ring back toward target so reporting error can't
	// slowly walk it away.
	//
	// srcBuf is the pre-resample scratch; phase is the fractional
	// source position carried across pulls (continuous-phase streaming
	// resample — no per-chunk splices); prevSrc is the final source
	// sample of the previous chunk, the interpolation anchor for the
	// next chunk's first outputs.
	ratio   float64 // applied resample ratio (source per output sample)
	errEMA  float64 // smoothed depth error (samples), centering input
	phase   float64
	prevSrc int16
	srcBuf  []int16
}

// oto permits exactly ONE audio context per process — a second
// oto.NewContext call crashes the audio driver. The context is also
// never torn down (Close only stops the player), so it is a natural
// process-singleton: created once, reused by every AudioSystem.
// This keeps GUI model switches (which build a fresh AudioSystem)
// and multi-test runs (each constructing emulators) from creating a
// second context and SIGSEGV-ing in the oto mux loop.
var (
	sharedCtxOnce sync.Once
	sharedCtx     *oto.Context
	sharedCtxErr  error

	// deviceBufferSize is the oto device buffer duration handed to
	// NewContext. Zero picks oto's platform default. Larger absorbs
	// host-scheduler jitter (fewer crackles) at the cost of latency;
	// set via SetDeviceBufferDuration BEFORE the first AudioSystem is
	// created (the context is a process singleton — later calls are
	// ineffective and log nothing).
	deviceBufferSize time.Duration
)

// SetMeasuredProductionRate reports the frontend's actual sample
// production rate (executed emulation frames × SamplesPerFrame per wall
// second — the frame loop's FPS measurement). The rate servo in the oto
// pull path consumes it; see prodRateBits for why the frontend reports
// this rather than the audio system inferring it. Call it periodically
// while RUNNING; do not call while paused (the last reported rate
// simply stays in effect for the cushion to bridge).
func (as *AudioSystem) SetMeasuredProductionRate(samplesPerSecond float64) {
	if samplesPerSecond > 0 {
		as.prodRateBits.Store(math.Float64bits(samplesPerSecond))
	}
}

// SetDeviceBufferDuration configures the audio device buffer used when
// the shared oto context is first created (`--audio-buffer-ms`). Must be
// called before the first AudioSystem construction to have any effect.
func SetDeviceBufferDuration(d time.Duration) {
	if d > 0 {
		deviceBufferSize = d
	}
}

func sharedAudioContext() (*oto.Context, error) {
	sharedCtxOnce.Do(func() {
		ctx, ready, err := oto.NewContext(&oto.NewContextOptions{
			SampleRate:   SampleRate,
			ChannelCount: ChannelCount,
			Format:       oto.FormatSignedInt16LE,
			BufferSize:   deviceBufferSize, // 0 = oto's platform default
		})
		if err != nil {
			sharedCtxErr = err
			return
		}
		waitAudioReady(ready)
		sharedCtx = ctx
	})
	return sharedCtx, sharedCtxErr
}

// New creates a new AudioSystem instance.
func New() (*AudioSystem, error) {
	as := &AudioSystem{keepAlive: defaultKeepAliveLevel}
	as.reader = &audioReader{
		audioSys:  as,
		buffer:    make([]byte, BufferSize*ChannelCount*2),
		mixBuffer: make([]int16, BufferSize),
		ditherRNG: 0x9E3779B9, // any non-zero seed
		ratio:     1.0,
		srcBuf:    make([]int16, BufferSize*2), // room for ratio up to 2.0
	}
	as.resetQueueCushioned()
	// On js the page owns playback: an AudioWorklet drains the ring via
	// PullMono after each emulated frame (see cmd/zx_go's zxPullAudio).
	// oto's browser backend — a deprecated main-thread ScriptProcessor
	// behind a 0.5s pre-read player buffer — is skipped entirely: it added
	// most of a second of latency and glitched whenever the emulator's own
	// frame work blocked the shared thread. player stays nil; Start/Stop
	// are no-ops.
	if runtime.GOOS == "js" {
		return as, nil
	}
	ctx, err := sharedAudioContext()
	if err != nil {
		return nil, fmt.Errorf("failed to create audio context: %w", err)
	}
	as.context = ctx
	as.player = ctx.NewPlayer(as.reader)
	// Bound the player's pre-read. oto's default player buffer is 0.5 s,
	// and audioReader.Read never blocks (underrun returns held-DC filler),
	// so an unbounded buffer sits PERMANENTLY full — heard as half a
	// second of constant audio lag behind the picture. Two read-chunks
	// (~46 ms) covers mux-goroutine wakeup jitter; stutter immunity lives
	// in the ring's underrunCushion hysteresis, and genuine starvation is
	// handled by the reader's DC filler — depth here buys only lag.
	as.player.SetBufferSize(BufferSize * ChannelCount * 2 * 2)
	return as, nil
}

// resetQueueCushioned empties the ring and arms the underrun hysteresis,
// so the next oto pulls deliver silence until a fresh underrunCushion of
// real samples has accumulated. Startup and machine reset both come
// through here: seeding actual silence samples (the old approach) added
// their whole duration to steady-state latency, whereas the armed
// cushion costs nothing once playback is flowing. The js pull path
// ignores cushioning (PullMono drains whatever is queued; the
// AudioWorklet keeps its own startup cushion).
func (as *AudioSystem) resetQueueCushioned() {
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	as.queueHead = 0
	as.queueTail = 0
	as.queueSize = 0
	as.lastSample = 0
	as.cushioning = true
}

// PushBeeperSamples enqueues a batch of mono beeper samples generated
// by the ULA at end of frame. The samples are consumed by the oto
// playback goroutine via Read. If the buffer would overflow (the
// playback goroutine is falling behind), the oldest samples are
// dropped — audio glitches are preferable to growing latency.
func (as *AudioSystem) PushBeeperSamples(samples []int16) {
	if len(samples) == 0 {
		return
	}
	for _, s := range samples { // diagnostic peak meter (see LastPeak)
		v := s
		if v < 0 {
			v = -v
		}
		if v > lastPeak {
			lastPeak = v
		}
	}
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	as.statPushed += uint64(len(samples))
	for _, s := range samples {
		as.queue[as.queueHead] = s
		as.queueHead = (as.queueHead + 1) % queueCapacity
		if as.queueSize == queueCapacity {
			// Buffer is full; advance tail to drop the oldest sample.
			as.queueTail = (as.queueTail + 1) % queueCapacity
			as.statDropped++
		} else {
			as.queueSize++
		}
	}
}

// underrunDecayNum/underrunDecayDen is the per-sample multiplier applied to
// the held level while the ring buffer is starved. ~255/256 gives a ~6 ms
// time constant: a brief gap is essentially held, but a sustained drain (a
// pause, a model switch, or a heavy fast-load tick that starves the producer)
// fades to silence rather than holding a flat DC plateau — a flat plateau
// would step abruptly back to the signal when production resumes, audible as
// a click.
const (
	underrunDecayNum = 255
	underrunDecayDen = 256
)

// popBeeperSamples drains up to len(out) samples from the ring buffer into
// out. Any unfilled slots continue from the last delivered sample and then
// decay toward 0, so underruns fade to silence smoothly instead of clicking.
//
// Underrun hysteresis: running dry arms `cushioning`, and while armed only
// the decaying held level is delivered — real samples resume once the
// producer has rebuilt underrunCushion of them. This pins the ring's
// steady-state depth at the cushion instead of ~0, where every
// producer/consumer phase wobble would otherwise interleave filler
// slivers as continuous stutter (see the underrunCushion doc comment).
func (as *AudioSystem) popBeeperSamples(out []int16) {
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	if as.cushioning && as.queueSize >= underrunCushion {
		as.cushioning = false
	}
	n := 0
	if !as.cushioning {
		for n < len(out) && as.queueSize > 0 {
			out[n] = as.queue[as.queueTail]
			as.queueTail = (as.queueTail + 1) % queueCapacity
			as.queueSize--
			n++
		}
		if n > 0 {
			as.lastSample = out[n-1]
		}
		if n < len(out) {
			// Ran dry mid-read: a true underrun. Rebuild the cushion
			// before delivering real samples again.
			as.cushioning = true
			as.statUnderruns++
		}
	}
	for ; n < len(out); n++ {
		out[n] = as.lastSample
		as.lastSample = int16(int32(as.lastSample) * underrunDecayNum / underrunDecayDen)
	}
}

// PullMono drains up to len(out) mixed mono samples (beeper + AY + DAC)
// from the system WITHOUT underrun padding, returning how many were
// written. This is the browser build's output path: the page pulls once
// per displayed frame and feeds an AudioWorklet, which owns the underrun
// and prebuffer policy on the audio render thread. The oto pull path
// (audioReader.Read) is never active on js, so the two do not race. The
// AY/DAC chips advance their internal clocks by exactly the samples
// consumed, keeping them aligned with the beeper timeline.
func (as *AudioSystem) PullMono(out []int16) int {
	as.queueMu.Lock()
	n := 0
	for n < len(out) && as.queueSize > 0 {
		out[n] = as.queue[as.queueTail]
		as.queueTail = (as.queueTail + 1) % queueCapacity
		as.queueSize--
		n++
	}
	if n > 0 {
		as.lastSample = out[n-1]
	}
	as.queueMu.Unlock()
	if n == 0 {
		return 0
	}
	buf := out[:n]

	as.ayMu.RLock()
	ay := as.ay
	as.ayMu.RUnlock()
	if ay != nil {
		ay.MixInto(buf)
	}

	as.dacMu.RLock()
	dac := as.dac
	as.dacMu.RUnlock()
	if dac != nil {
		dac.MixInto(buf)
	}

	as.writeRecording(buf)
	return n
}

// Read implements io.Reader for the audioReader. Pulls beeper samples
// from the ring buffer, mixes in any attached AY chip, then expands
// the mono mix to stereo for the oto sink.
func (ar *audioReader) Read(p []byte) (n int, err error) {
	bytesToRead := len(p)
	if bytesToRead > len(ar.buffer) {
		bytesToRead = len(ar.buffer)
	}
	samples := bytesToRead / (ChannelCount * 2)

	if cap(ar.mixBuffer) < samples {
		ar.mixBuffer = make([]int16, samples)
	}
	mixBuf := ar.mixBuffer[:samples]

	// Step 1: pull beeper samples through the rate-control servo (see the
	// audioReader field docs). Sample the ring depth, trim `ratio` toward
	// rate balance (frozen while the underrun cushion is rebuilding — the
	// ring holds only filler then), pop a ratio-scaled chunk, and
	// linearly resample it onto mixBuf.
	ar.audioSys.queueMu.Lock()
	depth := ar.audioSys.queueSize
	ar.audioSys.queueMu.Unlock()
	const (
		depthTarget = underrunCushion + SamplesPerFrame // ~80 ms — comfortably above the hysteresis watermark
		errAlpha    = 0.05                              // depth-error EMA: kills the ~7 Hz push/pull beat
		centerGain  = 2e-6                              // depth centering: ±900-sample wobble → ±0.18% trim
		centerClamp = 0.01                              // centering may never exceed ±1%
		ratioGlide  = 0.1                               // per-pull first-order glide toward the target ratio
		ratioMin    = 0.55                              // sustained-overload floor (45% slowdown)
		ratioMax    = 1.06                              // surplus drain ceiling
	)
	if need := int(float64(samples)*ratioMax) + 2; len(ar.srcBuf) < need {
		ar.srcBuf = make([]int16, need)
	}
	rate := math.Float64frombits(ar.audioSys.prodRateBits.Load())
	if rate <= 0 {
		rate = SampleRate // no frontend report yet (or non-GUI use): nominal
	}
	if samples > 0 {
		ar.errEMA += errAlpha * (float64(depth-depthTarget) - ar.errEMA)
	}
	centering := ar.errEMA * centerGain
	centering = math.Max(-centerClamp, math.Min(centerClamp, centering))
	target := math.Max(ratioMin, math.Min(ratioMax, rate/SampleRate+centering))
	if ar.ratio == 0 {
		ar.ratio = 1 // zero-value reader (tests construct the struct directly)
	}
	// Snap-to-unity: within snapBand of nominal the ratio pins to
	// EXACTLY 1.0 with zero phase, and audio takes the bit-exact copy
	// path below — the resampler engages only for genuine slowdown or a
	// depth-recentering excursion. This matters more than resampler
	// quality: fps-report noise (±0.2%) and the ever-present centering
	// trim would otherwise keep the resampler engaged 100% of the time
	// for no audible benefit.
	const snapBand = 0.002
	if math.Abs(target-1) < snapBand {
		target = 1
		if math.Abs(ar.ratio-1) < 5e-4 {
			ar.ratio = 1
			ar.phase = 0
		}
	}
	ar.ratio += ratioGlide * (target - ar.ratio)

	if ar.ratio == 1 && ar.phase == 0 {
		// Bit-exact path — identical to what the clean-sounding probe
		// exercises. This is the steady state on a healthy machine.
		ar.audioSys.popBeeperSamples(mixBuf)
		if samples > 0 {
			ar.prevSrc = mixBuf[samples-1]
		}
	} else if samples > 0 {
		// Streaming linear resampler with CONTINUOUS phase: output i
		// samples the source timeline at prev + phase + i*ratio, where
		// prev is the last source sample of the previous chunk. No
		// per-chunk endpoint splices — a splice per chunk on square
		// waves is an audible ~43 Hz click-buzz (the "complete shit"
		// regression this replaces).
		adv := ar.phase + float64(samples)*ar.ratio
		k := int(adv)
		if k > len(ar.srcBuf) { // safety; unreachable within ratio clamps
			k = len(ar.srcBuf)
			adv = float64(k)
		}
		ar.audioSys.popBeeperSamples(ar.srcBuf[:k])
		sample := func(idx int) int16 { // idx 0 = prev, idx j>0 = srcBuf[j-1]
			if idx <= 0 {
				return ar.prevSrc
			}
			if idx > k {
				idx = k // ≤1-sample tail clamp; next chunk continues smoothly
			}
			return ar.srcBuf[idx-1]
		}
		for i := 0; i < samples; i++ {
			q := ar.phase + float64(i)*ar.ratio
			lo := int(q)
			f := q - float64(lo)
			a := float64(sample(lo))
			b := float64(sample(lo + 1))
			mixBuf[i] = int16(a + f*(b-a))
		}
		ar.phase = adv - float64(k)
		if k > 0 {
			ar.prevSrc = ar.srcBuf[k-1]
		}
	}

	// Step 2: mix in the AY chip's output (it generates samples
	// from its own internal counters at audio rate).
	ar.audioSys.ayMu.RLock()
	ay := ar.audioSys.ay
	ar.audioSys.ayMu.RUnlock()
	if ay != nil {
		ay.MixInto(mixBuf)
	}

	// Step 2.5: mix in the Next DAC bank if attached (frame-snapshot
	// granularity — see DACSource).
	ar.audioSys.dacMu.RLock()
	dac := ar.audioSys.dac
	ar.audioSys.dacMu.RUnlock()
	if dac != nil {
		dac.MixInto(mixBuf)
	}

	// Step 3: WAV recording — append the mono mix before expansion (and
	// before the keep-alive dither, so captures stay clean for diagnostics).
	ar.audioSys.writeRecording(mixBuf)

	// Step 3.5: keep-alive dither — a sub-audible noise floor that stops the
	// host audio amp powering down during silence and popping on the next
	// sound. Added to the device output only.
	applyKeepAliveDither(mixBuf, ar.audioSys.keepAlive, &ar.ditherRNG)

	// Step 4: emit the mono mix as interleaved stereo bytes.
	for i := 0; i < samples; i++ {
		s := mixBuf[i]
		base := i * ChannelCount * 2
		ar.buffer[base] = byte(s)
		ar.buffer[base+1] = byte(s >> 8)
		ar.buffer[base+2] = byte(s)
		ar.buffer[base+3] = byte(s >> 8)
	}
	copy(p, ar.buffer[:bytesToRead])
	return bytesToRead, nil
}

// Start begins audio output. On js there is no oto player — playback is
// driven by the page pulling via PullMono — so this is a no-op there.
func (as *AudioSystem) Start() error {
	if as.player != nil {
		as.player.Play()
	}
	return nil
}

// Stop pauses audio output.
func (as *AudioSystem) Stop() {
	if as.player != nil {
		as.player.Pause()
	}
}

// SetAY attaches an AY-3-8912 source whose output will be mixed into
// the beeper stream. Pass nil to detach.
func (as *AudioSystem) SetAY(ay AYSource) {
	as.ayMu.Lock()
	defer as.ayMu.Unlock()
	as.ay = ay
}

// SetDAC attaches a Spectrum Next DAC bank whose output will be
// mixed into the beeper + AY stream. Pass nil to detach.
func (as *AudioSystem) SetDAC(dac DACSource) {
	as.dacMu.Lock()
	defer as.dacMu.Unlock()
	as.dac = dac
}

// SetKeepAliveLevel sets the peak amplitude of the sub-audible keep-alive
// dither (0 disables). Used to tune the level that stops the host audio amp
// powering down during silence without becoming audible.
func (as *AudioSystem) SetKeepAliveLevel(level int16) {
	if level < 0 {
		level = 0
	}
	as.keepAlive = level
}

// Close closes the audio system and releases resources.
func (as *AudioSystem) Close() error {
	as.Stop()
	_ = as.StopRecording()
	return nil
}

// Reset clears the beeper sample queue and re-seeds it with the
// startup silence cushion. Used on machine reset so the new session
// doesn't start with stale audio in the buffer AND immediately
// benefits from the same cushion that startup gets.
func (as *AudioSystem) Reset() {
	as.resetQueueCushioned()
}

// StartRecording opens path for writing and begins capturing the mixed
// mono audio output as a 16-bit PCM WAV file at SampleRate. If a
// recording is already in progress it is finalised first.
func (as *AudioSystem) StartRecording(path string) error {
	if err := as.StopRecording(); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create wav file: %w", err)
	}
	if err := writeWavHeader(f, 0, 1, SampleRate, 16); err != nil {
		_ = f.Close()
		_ = os.Remove(path)
		return fmt.Errorf("write wav header: %w", err)
	}
	as.recMu.Lock()
	as.recFile = f
	as.recSamples = 0
	as.recMu.Unlock()
	return nil
}

// maxWavSamples is the largest number of mono 16-bit samples we can
// capture before either of the WAV header's uint32 size fields would
// overflow. About 13.6 hours at 44.1kHz; writeRecording stops
// appending past this point.
const maxWavSamples uint64 = (0xFFFFFFFF - 36) / 2

// StopRecording finalises any in-progress recording.
func (as *AudioSystem) StopRecording() error {
	as.recMu.Lock()
	f := as.recFile
	samples := as.recSamples
	as.recFile = nil
	as.recSamples = 0
	as.recMu.Unlock()
	if f == nil {
		return nil
	}
	if _, err := f.Seek(0, 0); err != nil {
		_ = f.Close()
		return err
	}
	if err := writeWavHeader(f, uint32(samples), 1, SampleRate, 16); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}

// IsRecording reports whether a WAV recording is currently in progress.
func (as *AudioSystem) IsRecording() bool {
	as.recMu.Lock()
	defer as.recMu.Unlock()
	return as.recFile != nil
}

// writeRecording appends a mono sample buffer to the active WAV file.
func (as *AudioSystem) writeRecording(samples []int16) {
	as.recMu.Lock()
	defer as.recMu.Unlock()
	if as.recFile == nil {
		return
	}
	remaining := maxWavSamples - as.recSamples
	if remaining == 0 {
		return
	}
	n := uint64(len(samples))
	if n > remaining {
		n = remaining
		samples = samples[:n]
	}

	need := int(n) * 2
	if cap(as.recScratch) < need {
		as.recScratch = make([]byte, need)
	}
	buf := as.recScratch[:need]
	for i, s := range samples {
		binary.LittleEndian.PutUint16(buf[i*2:], uint16(s))
	}
	if _, err := as.recFile.Write(buf); err != nil {
		_ = as.recFile.Close()
		as.recFile = nil
		return
	}
	as.recSamples += n
}

// writeWavHeader writes a 44-byte canonical PCM WAV header.
func writeWavHeader(f *os.File, sampleCount uint32, channels uint16, sampleRate uint32, bitsPerSample uint16) error {
	byteRate := sampleRate * uint32(channels) * uint32(bitsPerSample) / 8
	blockAlign := channels * bitsPerSample / 8
	dataSize := sampleCount * uint32(blockAlign)
	riffSize := 36 + dataSize

	hdr := make([]byte, 44)
	copy(hdr[0:4], []byte("RIFF"))
	binary.LittleEndian.PutUint32(hdr[4:8], riffSize)
	copy(hdr[8:12], []byte("WAVE"))
	copy(hdr[12:16], []byte("fmt "))
	binary.LittleEndian.PutUint32(hdr[16:20], 16)
	binary.LittleEndian.PutUint16(hdr[20:22], 1)
	binary.LittleEndian.PutUint16(hdr[22:24], channels)
	binary.LittleEndian.PutUint32(hdr[24:28], sampleRate)
	binary.LittleEndian.PutUint32(hdr[28:32], byteRate)
	binary.LittleEndian.PutUint16(hdr[32:34], blockAlign)
	binary.LittleEndian.PutUint16(hdr[34:36], bitsPerSample)
	copy(hdr[36:40], []byte("data"))
	binary.LittleEndian.PutUint32(hdr[40:44], dataSize)

	_, err := f.Write(hdr)
	return err
}
