package audio

import (
	"encoding/binary"
	"fmt"
	"os"
	"runtime"
	"sync"
	"time"

	"github.com/ebitengine/oto/v3"
)

// AYSource is the minimal interface that the audio system needs from an AY
// sound chip implementation. It is satisfied by *ay.AY but kept as an
// interface here so the audio package does not need to import the ay package
// (which would create a dependency cycle through the ULA).
type AYSource interface {
	MixInto(buf []int16)
}

// DACSource is the minimal interface for the Spectrum Next's four
// 8-bit DACs. Satisfied by *next/dac.Bank. Mixes at frame-snapshot
// granularity: the current level is applied uniformly across the
// whole buffer rather than integrating individual writes within
// the frame (contrast pkg/audiodac's event-based reconstruction).
type DACSource interface {
	MixInto(buf []int16)
}

const (
	// Audio parameters
	SampleRate   = 44100
	ChannelCount = 2    // Stereo
	BitDepth     = 16   // 16-bit
	BufferSize   = 1024 // oto buffer size in samples — small enough that Read() runs ~43 times/sec, keeping playback latency low

	// SamplesPerFrame is the number of mono beeper samples one
	// emulator frame produces at SampleRate / 50Hz. The ULA pushes
	// exactly this many samples to the audio system per frame.
	SamplesPerFrame = SampleRate / 50

	// queueCapacity is the ring buffer size in mono samples — about
	// 12 frames at 50Hz (~240 ms). Wide enough to absorb scheduler
	// jitter, GC pauses, and the natural push/pull oscillation
	// between the 50Hz producer and the ~43Hz consumer.
	queueCapacity = SamplesPerFrame * 12

	// queuePrefill is how many silence samples we seed the queue
	// with at startup so the consumer's first pull doesn't drain
	// the queue to zero. Without this cushion, the producer is
	// always exactly one push behind the consumer (they have equal
	// average rates but different periods), and every pull cycle
	// returns a partial buffer plus DC silence — audible as
	// stutter at the consumer's pull rate. Four frames give the
	// queue enough headroom that the discrete-event oscillation
	// never reaches the bottom.
	queuePrefill = SamplesPerFrame * 4
)

// prefillSilence indexes queue (a [queueCapacity]int16 array) directly over
// [0, queuePrefill); this compile-time check keeps that in bounds if either
// constant's multiplier above is ever changed on its own.
var _ [queueCapacity - queuePrefill]struct{}

// AudioSystem handles audio output for the ZX Spectrum beeper and (on 128K+
// machines) the AY-3-8912 sound chip.
//
// The beeper input is event-driven: the ULA records every speaker bit
// toggle during the frame with the T-state at which it happened, and at
// end of frame generates a fresh batch of SamplesPerFrame mono samples
// that gets pushed via PushBeeperSamples. The oto playback callback
// pulls samples from the ring buffer; on underflow it holds the last
// sample (DC) instead of clicking.
//
// The AY chip is mixed in by the playback callback at audio-sample
// rate via AYSource.MixInto, since AY samples are generated by the
// chip's own internal counters and don't need event-time alignment.
type AudioSystem struct {
	context *oto.Context
	player  *oto.Player
	reader  *audioReader

	// Beeper sample ring buffer.
	queueMu    sync.Mutex
	queue      [queueCapacity]int16
	queueHead  int   // next write position
	queueTail  int   // next read position
	queueSize  int   // number of samples currently in the buffer
	lastSample int16 // value to hold during underflow (DC, no clicks)

	// Optional AY-3-8912 source.
	ayMu sync.RWMutex
	ay   AYSource

	// Optional Spectrum Next DAC source.
	dacMu sync.RWMutex
	dac   DACSource

	// keepAlive is the peak amplitude of the sub-audible dither mixed into the
	// output to stop the host audio amp powering down during silence (and
	// popping on the next sound). 0 disables. Read/written only on the oto
	// goroutine path + setup, so a plain field is fine.
	keepAlive int16

	// WAV recording state. When recFile is non-nil the audio reader
	// appends each generated sample to the file as 16-bit mono PCM.
	recMu      sync.Mutex
	recFile    *os.File
	recSamples uint64
	recScratch []byte
}

// audioReader implements io.Reader on the oto playback goroutine.
type audioReader struct {
	audioSys  *AudioSystem
	buffer    []byte
	mixBuffer []int16
	ditherRNG uint32 // xorshift32 state for the keep-alive dither
}

// oto permits exactly ONE audio context per process — a second
// oto.NewContext call crashes the audio driver. The context is also
// never torn down (Close only stops the player), so it is a natural
// process-singleton: created once, reused by every AudioSystem.
// This keeps GUI model switches (which build a fresh AudioSystem)
// and multi-test runs (each constructing emulators) from creating a
// second context and SIGSEGV-ing in the oto mux loop.
var (
	sharedCtxOnce sync.Once
	sharedCtx     *oto.Context
	sharedCtxErr  error

	// deviceBufferSize is the oto device buffer duration handed to
	// NewContext. Zero picks oto's platform default. Larger absorbs
	// host-scheduler jitter (fewer crackles) at the cost of latency;
	// set via SetDeviceBufferDuration BEFORE the first AudioSystem is
	// created (the context is a process singleton — later calls are
	// ineffective and log nothing).
	deviceBufferSize time.Duration
)

// SetDeviceBufferDuration configures the audio device buffer used when
// the shared oto context is first created (`--audio-buffer-ms`). Must be
// called before the first AudioSystem construction to have any effect.
func SetDeviceBufferDuration(d time.Duration) {
	if d > 0 {
		deviceBufferSize = d
	}
}

func sharedAudioContext() (*oto.Context, error) {
	sharedCtxOnce.Do(func() {
		ctx, ready, err := oto.NewContext(&oto.NewContextOptions{
			SampleRate:   SampleRate,
			ChannelCount: ChannelCount,
			Format:       oto.FormatSignedInt16LE,
			BufferSize:   deviceBufferSize, // 0 = oto's platform default
		})
		if err != nil {
			sharedCtxErr = err
			return
		}
		waitAudioReady(ready)
		sharedCtx = ctx
	})
	return sharedCtx, sharedCtxErr
}

// New creates a new AudioSystem instance.
func New() (*AudioSystem, error) {
	as := &AudioSystem{keepAlive: defaultKeepAliveLevel}
	as.reader = &audioReader{
		audioSys:  as,
		buffer:    make([]byte, BufferSize*ChannelCount*2),
		mixBuffer: make([]int16, BufferSize),
		ditherRNG: 0x9E3779B9, // any non-zero seed
	}
	as.prefillSilence()
	// On js the page owns playback: an AudioWorklet drains the ring via
	// PullMono after each emulated frame (see cmd/zx_go's zxPullAudio).
	// oto's browser backend — a deprecated main-thread ScriptProcessor
	// behind a 0.5s pre-read player buffer — is skipped entirely: it added
	// most of a second of latency and glitched whenever the emulator's own
	// frame work blocked the shared thread. player stays nil; Start/Stop
	// are no-ops.
	if runtime.GOOS == "js" {
		return as, nil
	}
	ctx, err := sharedAudioContext()
	if err != nil {
		return nil, fmt.Errorf("failed to create audio context: %w", err)
	}
	as.context = ctx
	as.player = ctx.NewPlayer(as.reader)
	return as, nil
}

// prefillSilence seeds the ring buffer with queuePrefill silent
// samples so the consumer's first few pulls are satisfied without
// draining the queue. See the queuePrefill doc comment for the rate-
// matching reasoning.
func (as *AudioSystem) prefillSilence() {
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	prefill := queuePrefill
	if runtime.GOOS == "js" {
		// The js pull path (PullMono → AudioWorklet) drains whatever is
		// queued, so seeded silence would just play first and delay every
		// real sample behind it by the prefill. The worklet keeps its own
		// startup cushion instead.
		prefill = 0
	}
	as.queueHead = prefill % queueCapacity
	as.queueTail = 0
	as.queueSize = prefill
	for i := 0; i < prefill; i++ {
		as.queue[i] = 0
	}
	as.lastSample = 0
}

// PushBeeperSamples enqueues a batch of mono beeper samples generated
// by the ULA at end of frame. The samples are consumed by the oto
// playback goroutine via Read. If the buffer would overflow (the
// playback goroutine is falling behind), the oldest samples are
// dropped — audio glitches are preferable to growing latency.
func (as *AudioSystem) PushBeeperSamples(samples []int16) {
	if len(samples) == 0 {
		return
	}
	for _, s := range samples { // diagnostic peak meter (see LastPeak)
		v := s
		if v < 0 {
			v = -v
		}
		if v > lastPeak {
			lastPeak = v
		}
	}
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	for _, s := range samples {
		as.queue[as.queueHead] = s
		as.queueHead = (as.queueHead + 1) % queueCapacity
		if as.queueSize == queueCapacity {
			// Buffer is full; advance tail to drop the oldest sample.
			as.queueTail = (as.queueTail + 1) % queueCapacity
		} else {
			as.queueSize++
		}
	}
}

// underrunDecayNum/underrunDecayDen is the per-sample multiplier applied to
// the held level while the ring buffer is starved. ~255/256 gives a ~6 ms
// time constant: a brief gap is essentially held, but a sustained drain (a
// pause, a model switch, or a heavy fast-load tick that starves the producer)
// fades to silence rather than holding a flat DC plateau — a flat plateau
// would step abruptly back to the signal when production resumes, audible as
// a click.
const (
	underrunDecayNum = 255
	underrunDecayDen = 256
)

// popBeeperSamples drains up to len(out) samples from the ring buffer into
// out. Any unfilled slots continue from the last delivered sample and then
// decay toward 0, so underruns fade to silence smoothly instead of clicking.
// Returns the slice unchanged.
func (as *AudioSystem) popBeeperSamples(out []int16) {
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	n := 0
	for n < len(out) && as.queueSize > 0 {
		out[n] = as.queue[as.queueTail]
		as.queueTail = (as.queueTail + 1) % queueCapacity
		as.queueSize--
		n++
	}
	if n > 0 {
		as.lastSample = out[n-1]
	}
	for ; n < len(out); n++ {
		out[n] = as.lastSample
		as.lastSample = int16(int32(as.lastSample) * underrunDecayNum / underrunDecayDen)
	}
}

// PullMono drains up to len(out) mixed mono samples (beeper + AY + DAC)
// from the system WITHOUT underrun padding, returning how many were
// written. This is the browser build's output path: the page pulls once
// per displayed frame and feeds an AudioWorklet, which owns the underrun
// and prebuffer policy on the audio render thread. The oto pull path
// (audioReader.Read) is never active on js, so the two do not race. The
// AY/DAC chips advance their internal clocks by exactly the samples
// consumed, keeping them aligned with the beeper timeline.
func (as *AudioSystem) PullMono(out []int16) int {
	as.queueMu.Lock()
	n := 0
	for n < len(out) && as.queueSize > 0 {
		out[n] = as.queue[as.queueTail]
		as.queueTail = (as.queueTail + 1) % queueCapacity
		as.queueSize--
		n++
	}
	if n > 0 {
		as.lastSample = out[n-1]
	}
	as.queueMu.Unlock()
	if n == 0 {
		return 0
	}
	buf := out[:n]

	as.ayMu.RLock()
	ay := as.ay
	as.ayMu.RUnlock()
	if ay != nil {
		ay.MixInto(buf)
	}

	as.dacMu.RLock()
	dac := as.dac
	as.dacMu.RUnlock()
	if dac != nil {
		dac.MixInto(buf)
	}

	as.writeRecording(buf)
	return n
}

// Read implements io.Reader for the audioReader. Pulls beeper samples
// from the ring buffer, mixes in any attached AY chip, then expands
// the mono mix to stereo for the oto sink.
func (ar *audioReader) Read(p []byte) (n int, err error) {
	bytesToRead := len(p)
	if bytesToRead > len(ar.buffer) {
		bytesToRead = len(ar.buffer)
	}
	samples := bytesToRead / (ChannelCount * 2)

	if cap(ar.mixBuffer) < samples {
		ar.mixBuffer = make([]int16, samples)
	}
	mixBuf := ar.mixBuffer[:samples]

	// Step 1: pull beeper samples from the ULA's ring buffer.
	ar.audioSys.popBeeperSamples(mixBuf)

	// Step 2: mix in the AY chip's output (it generates samples
	// from its own internal counters at audio rate).
	ar.audioSys.ayMu.RLock()
	ay := ar.audioSys.ay
	ar.audioSys.ayMu.RUnlock()
	if ay != nil {
		ay.MixInto(mixBuf)
	}

	// Step 2.5: mix in the Next DAC bank if attached (frame-snapshot
	// granularity — see DACSource).
	ar.audioSys.dacMu.RLock()
	dac := ar.audioSys.dac
	ar.audioSys.dacMu.RUnlock()
	if dac != nil {
		dac.MixInto(mixBuf)
	}

	// Step 3: WAV recording — append the mono mix before expansion (and
	// before the keep-alive dither, so captures stay clean for diagnostics).
	ar.audioSys.writeRecording(mixBuf)

	// Step 3.5: keep-alive dither — a sub-audible noise floor that stops the
	// host audio amp powering down during silence and popping on the next
	// sound. Added to the device output only.
	applyKeepAliveDither(mixBuf, ar.audioSys.keepAlive, &ar.ditherRNG)

	// Step 4: emit the mono mix as interleaved stereo bytes.
	for i := 0; i < samples; i++ {
		s := mixBuf[i]
		base := i * ChannelCount * 2
		ar.buffer[base] = byte(s)
		ar.buffer[base+1] = byte(s >> 8)
		ar.buffer[base+2] = byte(s)
		ar.buffer[base+3] = byte(s >> 8)
	}
	copy(p, ar.buffer[:bytesToRead])
	return bytesToRead, nil
}

// Start begins audio output. On js there is no oto player — playback is
// driven by the page pulling via PullMono — so this is a no-op there.
func (as *AudioSystem) Start() error {
	if as.player != nil {
		as.player.Play()
	}
	return nil
}

// Stop pauses audio output.
func (as *AudioSystem) Stop() {
	if as.player != nil {
		as.player.Pause()
	}
}

// SetAY attaches an AY-3-8912 source whose output will be mixed into
// the beeper stream. Pass nil to detach.
func (as *AudioSystem) SetAY(ay AYSource) {
	as.ayMu.Lock()
	defer as.ayMu.Unlock()
	as.ay = ay
}

// SetDAC attaches a Spectrum Next DAC bank whose output will be
// mixed into the beeper + AY stream. Pass nil to detach.
func (as *AudioSystem) SetDAC(dac DACSource) {
	as.dacMu.Lock()
	defer as.dacMu.Unlock()
	as.dac = dac
}

// SetKeepAliveLevel sets the peak amplitude of the sub-audible keep-alive
// dither (0 disables). Used to tune the level that stops the host audio amp
// powering down during silence without becoming audible.
func (as *AudioSystem) SetKeepAliveLevel(level int16) {
	if level < 0 {
		level = 0
	}
	as.keepAlive = level
}

// Close closes the audio system and releases resources.
func (as *AudioSystem) Close() error {
	as.Stop()
	_ = as.StopRecording()
	return nil
}

// Reset clears the beeper sample queue and re-seeds it with the
// startup silence cushion. Used on machine reset so the new session
// doesn't start with stale audio in the buffer AND immediately
// benefits from the same cushion that startup gets.
func (as *AudioSystem) Reset() {
	as.prefillSilence()
}

// StartRecording opens path for writing and begins capturing the mixed
// mono audio output as a 16-bit PCM WAV file at SampleRate. If a
// recording is already in progress it is finalised first.
func (as *AudioSystem) StartRecording(path string) error {
	if err := as.StopRecording(); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create wav file: %w", err)
	}
	if err := writeWavHeader(f, 0, 1, SampleRate, 16); err != nil {
		_ = f.Close()
		_ = os.Remove(path)
		return fmt.Errorf("write wav header: %w", err)
	}
	as.recMu.Lock()
	as.recFile = f
	as.recSamples = 0
	as.recMu.Unlock()
	return nil
}

// maxWavSamples is the largest number of mono 16-bit samples we can
// capture before either of the WAV header's uint32 size fields would
// overflow. About 13.6 hours at 44.1kHz; writeRecording stops
// appending past this point.
const maxWavSamples uint64 = (0xFFFFFFFF - 36) / 2

// StopRecording finalises any in-progress recording.
func (as *AudioSystem) StopRecording() error {
	as.recMu.Lock()
	f := as.recFile
	samples := as.recSamples
	as.recFile = nil
	as.recSamples = 0
	as.recMu.Unlock()
	if f == nil {
		return nil
	}
	if _, err := f.Seek(0, 0); err != nil {
		_ = f.Close()
		return err
	}
	if err := writeWavHeader(f, uint32(samples), 1, SampleRate, 16); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}

// IsRecording reports whether a WAV recording is currently in progress.
func (as *AudioSystem) IsRecording() bool {
	as.recMu.Lock()
	defer as.recMu.Unlock()
	return as.recFile != nil
}

// writeRecording appends a mono sample buffer to the active WAV file.
func (as *AudioSystem) writeRecording(samples []int16) {
	as.recMu.Lock()
	defer as.recMu.Unlock()
	if as.recFile == nil {
		return
	}
	remaining := maxWavSamples - as.recSamples
	if remaining == 0 {
		return
	}
	n := uint64(len(samples))
	if n > remaining {
		n = remaining
		samples = samples[:n]
	}

	need := int(n) * 2
	if cap(as.recScratch) < need {
		as.recScratch = make([]byte, need)
	}
	buf := as.recScratch[:need]
	for i, s := range samples {
		binary.LittleEndian.PutUint16(buf[i*2:], uint16(s))
	}
	if _, err := as.recFile.Write(buf); err != nil {
		_ = as.recFile.Close()
		as.recFile = nil
		return
	}
	as.recSamples += n
}

// writeWavHeader writes a 44-byte canonical PCM WAV header.
func writeWavHeader(f *os.File, sampleCount uint32, channels uint16, sampleRate uint32, bitsPerSample uint16) error {
	byteRate := sampleRate * uint32(channels) * uint32(bitsPerSample) / 8
	blockAlign := channels * bitsPerSample / 8
	dataSize := sampleCount * uint32(blockAlign)
	riffSize := 36 + dataSize

	hdr := make([]byte, 44)
	copy(hdr[0:4], []byte("RIFF"))
	binary.LittleEndian.PutUint32(hdr[4:8], riffSize)
	copy(hdr[8:12], []byte("WAVE"))
	copy(hdr[12:16], []byte("fmt "))
	binary.LittleEndian.PutUint32(hdr[16:20], 16)
	binary.LittleEndian.PutUint16(hdr[20:22], 1)
	binary.LittleEndian.PutUint16(hdr[22:24], channels)
	binary.LittleEndian.PutUint32(hdr[24:28], sampleRate)
	binary.LittleEndian.PutUint32(hdr[28:32], byteRate)
	binary.LittleEndian.PutUint16(hdr[32:34], blockAlign)
	binary.LittleEndian.PutUint16(hdr[34:36], bitsPerSample)
	copy(hdr[36:40], []byte("data"))
	binary.LittleEndian.PutUint32(hdr[40:44], dataSize)

	_, err := f.Write(hdr)
	return err
}
