type Mutation {
  compile(
    basic: String!
    files: [ProjectFileInput!]
  ): CompileResult
}

type Mutation {
  compileC(
    code: String!
    files: [ProjectFileInput!]
  ): CompileResult
}

type Mutation {
  compileSjasmplus(
    code: String!
    files: [ProjectFileInput!]
  ): CompileResult
}

type Mutation {
  compilePascal(
    code: String!
    machine: String
    files: [ProjectFileInput!]
  ): CompileResult
}

input ProjectFileInput {
  name: String!
  content: String!
  is_binary: Boolean
}

type CompileResult {
  base64_encoded: String!
  sld: String
}

