// Generates packages/ui/theme.css from primereact's compiled md-dark-indigo
// theme by remapping the indigo primary palette to the ZX Play cyan.
//
// primereact 9 ships only compiled theme CSS (no SCSS sources), and the theme
// bakes literal colours into every component rule rather than using CSS
// variables — so overriding --primary-color at runtime does nothing. The whole
// indigo primary is a single RGB triple (159,168,218), written as #9FA8DA or
// rgba(159,168,218,a). Substituting that triple retints every primary-coloured
// component at once while preserving all the hover/active/opacity logic.
//
// Re-run after bumping primereact:  node packages/ui/build-theme.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));

const SRC = require.resolve(
  "primereact/resources/themes/md-dark-indigo/theme.css"
);
const OUT = join(here, "theme.css");

// indigo primary -> ZX Play cyan (#2BD4D4 == rgb 43,212,218 -> 43,212,212)
const CYAN_HEX = "#2BD4D4";
const CYAN_RGB = "43, 212, 212";

let css = readFileSync(SRC, "utf8");

// Drop the bundled Roboto @font-face blocks: they reference ./fonts/* relative
// to the source file, which would 404 from the package, and both apps use the
// system font stack anyway.
css = css.replace(/@font-face\s*\{[^}]*\}/g, "");

// Remap the primary palette.
css = css.replace(/#9fa8da/gi, CYAN_HEX);
css = css.replace(/rgba\(159,\s*168,\s*218,/g, `rgba(${CYAN_RGB},`);
css = css.replace(/#e8eaf6/gi, "#d6f5f5"); // single light-indigo tint -> light cyan

const banner =
  "/* GENERATED by packages/ui/build-theme.mjs from primereact md-dark-indigo.\n" +
  "   Do not edit by hand. Re-run the generator after bumping primereact. */\n";

writeFileSync(OUT, banner + css.trimStart());
console.log(`wrote ${OUT} (${css.length} bytes, primary remapped to ${CYAN_HEX})`);
